### ISSUE TITLE
The pretrained human segmenter seems not provided

### ISSUE THREAD

**Issue by xinyao240** [AnyiRao/video_unscreen#1]
Hi, thanks for your great work!

I notice that in [configs](https://github.com/AnyiRao/video_unscreen/tree/master/configs)/bg.json, the config of the pre-trained binary segmenter is 
"binseg": {
        "model_path": "./weights/exp-schp-201908261155-lip.pth",
        "input_long_side": 962,
        "stride_ratio": 0.5,
        "flip": true
    },
where the pre-trained model with file name "exp-schp-201908261155-lip.pth" seems not provided in the provided Google drive link(https://drive.google.com/drive/folders/1IYcUaimgllu_PyE6jBHDgn8FfD4stdkW?usp=sharing).
I tried all the provided pre-trained models but none of them match the structure of the human segmenter used in bg.py. I wonder if the pre-trained model is missed and if possible, could you upload that pre-trained model?

Looking forward to your reply

**Comment by anyirao** [comment]
Hi,

Thanks for your interest in this project and your kind reminder. It is uploaded.

Best,

**Comment by xinyao240** [comment]
> Hi,
> 
> Thanks for your interest in this project and your kind reminder. It is uploaded.
> 
> Best,

Thanks.
